"""initial schema

Revision ID: 60af6b288466
Revises: 
Create Date: 2026-07-26 12:55:29.105022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60af6b288466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_query_logs',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('owner_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='projectmemberrole', native_enum=False), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uk_project_user')
    )
    op.create_table('trouble_documents',
    sa.Column('project_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('author_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('retrospective', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trouble_documents_author_id'), 'trouble_documents', ['author_id'], unique=False)
    op.create_index(op.f('ix_trouble_documents_project_id'), 'trouble_documents', ['project_id'], unique=False)
    op.create_table('ai_query_citations',
    sa.Column('ai_query_log_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('document_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ai_query_log_id'], ['ai_query_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['trouble_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_query_citations_ai_query_log_id'), 'ai_query_citations', ['ai_query_log_id'], unique=False)
    op.create_index(op.f('ix_ai_query_citations_document_id'), 'ai_query_citations', ['document_id'], unique=False)
    op.create_table('attachments',
    sa.Column('document_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('LOG', 'PDF', 'MARKDOWN', 'IMAGE', name='attachmentfiletype', native_enum=False), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['trouble_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_document_id'), 'attachments', ['document_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('document_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['trouble_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uk_bookmark_user_doc')
    )
    op.create_table('comments',
    sa.Column('document_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('author_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['trouble_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_document_id'), 'comments', ['document_id'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('document_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=100), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['trouble_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_id')
    )
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('tag_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['trouble_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('recent_views',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('document_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['trouble_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_id', name='uk_recentview_user_doc')
    )
    op.create_index(op.f('ix_recent_views_user_id'), 'recent_views', ['user_id'], unique=False)

    # NOTE(ERD 설계 노트): MySQL FULLTEXT는 SQLAlchemy Core/ORM으로 표현할 수 없어
    # raw DDL로 별도 추가한다. SQLite 등 다른 방언(테스트 환경 포함)에서는 건너뛴다.
    if op.get_bind().dialect.name == 'mysql':
        op.execute(
            "ALTER TABLE trouble_documents "
            "ADD FULLTEXT INDEX ft_doc_search (title, problem_description, error_message)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == 'mysql':
        op.execute("ALTER TABLE trouble_documents DROP INDEX ft_doc_search")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recent_views_user_id'), table_name='recent_views')
    op.drop_table('recent_views')
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_comments_document_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_attachments_document_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_ai_query_citations_document_id'), table_name='ai_query_citations')
    op.drop_index(op.f('ix_ai_query_citations_ai_query_log_id'), table_name='ai_query_citations')
    op.drop_table('ai_query_citations')
    op.drop_index(op.f('ix_trouble_documents_project_id'), table_name='trouble_documents')
    op.drop_index(op.f('ix_trouble_documents_author_id'), table_name='trouble_documents')
    op.drop_table('trouble_documents')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('ai_query_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
